### ISSUE TITLE
Alpha 2

### ISSUE THREAD

**Issue by joostruis** [fsvm88/cosmic-overlay#12]
Looks like there is a new version https://github.com/pop-os/cosmic-epoch

I guess this is the alpha 2 version?

**Comment by fsvm88** [comment]
I added all the work in the referenced PR, including src_install resyncs for 9999 and some deps fixes.

I haven't had time to test it yet. Please feel free to review and test (I should have more time over the weekend).

**Comment by joostruis** [comment]
I can help build test it once it is merged. Take your time!

**Comment by joostruis** [comment]
Is there any objection for you to merge the PR now? Then I can give it a test build.

**Comment by fsvm88** [comment]
Managed to test it: resolved a couple bugs with some packages.

I can successfully compile+install all ebuilds for alpha1/alpha2 now.

Work for alpha2  is also included in 9999 ebuilds.
