### ISSUE TITLE
cosmic-de/cosmic-settings-daemon: make media-sound/ playerctl optional?

### ISSUE THREAD

**Issue by joostruis** [fsvm88/cosmic-overlay#14]
I noticed that cosmic-de/cosmic-settings-daemon now pulls in media-sound/ playerctl, could this be made optional and controlled by the mpris use flag?

**Comment by fsvm88** [comment]
Agree, right now it's implemented via actions, no code involved (only configuration), so I do not expect it to break anything.

Already pushed, feel free to test and report :)

**Comment by joostruis** [comment]
Works for me, thanks!
