### ISSUE TITLE
cosmic-greeter PAM issue

### ISSUE THREAD

**Issue by joostruis** [fsvm88/cosmic-overlay#15]
I can't seem to get cosmic-greeter to start anymore. This used to work a while ago though.

What I can see in my logs:
```
Sep 30 17:27:01 xbox-360 systemd[1]: cosmic-greeter.service: Scheduled restart job, restart counter is at 1.
Sep 30 17:27:01 xbox-360 systemd[1]: Started COSMIC Greeter.
Sep 30 17:27:01 xbox-360 greetd[1146]: error: PAM 'cosmic-greeter' service missing
```

I do have the file for it installed:
```
joost@xbox-360 ~ $ ls -la /etc/pam.d/cosmic-greeter.pam 
-rw-r--r-- 1 root root 1320 Sep 29 23:03 /etc/pam.d/cosmic-greeter.pam
joost@xbox-360 ~ $ cat /etc/pam.d/cosmic-greeter.pam
#%PAM-1.0
auth    requisite       pam_nologin.so
auth    required        pam_succeed_if.so user != root quiet_success
@include common-auth
auth    optional        pam_gnome_keyring.so
@include common-account
# SELinux needs to be the first session rule. This ensures that any 
# lingering context has been cleared. Without this it is possible 
# that a module could execute code in the wrong domain.
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
session required        pam_loginuid.so
# SELinux needs to intervene at login time to ensure that the process
# starts in the proper default security context. Only sessions which are
# intended to run in the user's context should be run after this.
# pam_selinux.so changes the SELinux context of the used TTY and configures
# SELinux in order to transition to the user context with the next execve()
# call.
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open
session optional        pam_keyinit.so force revoke
session required        pam_limits.so
session required        pam_env.so readenv=1
session required        pam_env.so readenv=1 user_readenv=1 envfile=/etc/default/locale
@include common-session
session optional        pam_gnome_keyring.so auto_start
@include common-password
```

Not sure if it matters but the file has an extension (.pam) while other files in this directory don't

**Comment by fsvm88** [comment]
#17 technically fixed the fact that the PAM file was not being read, but I get tons of errors related to `@include` directives and an error with the selinux module. In the end, `cosmic-greeter` still doesn't start for me.

Reopening and further debugging with PAM later.

**Comment by filmor** [comment]
I guess this PAM file is just to Debian-specific. Previous issues with the Fedora builds of cosmic could be "fixed" by using the `greetd` PAM config, maybe this would be a good first step here as well?

**Comment by joostruis** [comment]
Thanks. I noticed Arch resolved this by creating a symlink to that login file, but I guess this solution is even better.

**Comment by fsvm88** [comment]
> I guess this PAM file is just to Debian-specific. Previous issues with the Fedora builds of cosmic could be "fixed" by using the `greetd` PAM config, maybe this would be a good first step here as well?

Yes, agreed.

As suggested, I simply copy-pasted `/etc/pam.d/greetd`, and cosmic-greeter started successfully. It's now shipped in $FILESDIR for the foreseeable future, I believe it anyway covers 99% of use-cases, and cosmic-greeter relies on greetd as well.
