### ISSUE TITLE
Contact with upstream

### ISSUE THREAD

**Issue by joostruis** [fsvm88/cosmic-overlay#19]
Hi. I just took the initiative to point out the work done on this overlay to upstream system76. I've asked[1] for a honorable mention of the work on their website as they also provide information on how to install Cosmic on other distributions.

In response upstream asked to elaborate and hook up with them (and other packagers from other distributions) so we all could share efforts. And I must say I like this approach. 

Having said all this. Feel free to contact upstream directly here: chat.pop-os.org (it is an open invite)

 [1] https://allthingstech.social/@joostruis/113234370160853760
 
 Cheers!

**Comment by fsvm88** [comment]
Hi! Oh wow, thanks! :)

I agree with the approach :)

I joined their chat, I'll probably reach out in the next days, as the week is quite busy :)

**Comment by fsvm88** [comment]
This is done. I checked in with Jeremy and am following the Pop!_OS MM channels.

Resolving :)
