### ISSUE TITLE
cosmic-de/cosmic-osd bad checksum

### ISSUE THREAD

**Issue by sebasmagri** [fsvm88/cosmic-overlay#20]
I'm getting this while emerging cosmic-osd:

```
 * cargo build --profile release-maximum-optimization
error: the listed checksum of `/var/tmp/portage/cosmic-de/cosmic-osd-1.0.0_alpha2/work/cargo_home/gentoo/x11rb-protocol/src/protocol/xf86dri.rs` has changed:
expected: 36e50d31d671942bbd929800c9df4a4a7b01fdb8bf5fe41a19c971dc068e40ac
actual:   9153e9f3eb7e4ac2c4401fee3aa9dc268f706fb69481063c8232e10f6765af0b
```

**Comment by fsvm88** [comment]
That error is saying that the file at `/var/tmp/portage/.../cargo_home/gentoo/x11rb-protocol/src/protocol/xf86dri.rs` has a different checksum than the one that was vendored in the `unpack` phase.

If you rerun the emerge command, does this happen consistently?

I'm not sure how that can happen, unless you change the file manually after running the `unpack` phase, or perhaps you have bad SSD or RAM.


The longer explanation:

Being handled through git (for lack of an easier option at the moment) means:
1. Repository is cloned/updated at `$DISTDIR`
2. Crates are fetched in the `unpack` phase to `$DISTDIR/cargo-registry`
3. Crates are `vendored` (copied in the temporary build dir) in the `unpack` phase to `/var/tmp/portage/.../work/cargo_home/`
4. `compile` phase runs `cargo build` using the crates from the temporary build dir, at `cargo_home`

So unless something happened between 3 and 4, the files should remain the same, their digest is not part of the ebuild at the moment.

**Comment by fsvm88** [comment]
No feedback  for ~1mo. Resolving.
