### ISSUE TITLE
cosmic-de/cosmic-settings-daemon manifest

### ISSUE THREAD

**Issue by joostruis** [fsvm88/cosmic-overlay#26]
!!! Digest verification failed:
!!! /var/db/repos/cosmic-overlay/cosmic-de/cosmic-settings-daemon/cosmic-settings-daemon-1.0.0_alpha1.ebuild
!!! Reason: Filesize does not match recorded size
!!! Got: 824
!!! Expected: 782

**Comment by fsvm88** [comment]
Hey @joostruis , sorry, merged a PR a couple days ago and that likely broke it.

I literally just merged a PR switching to thin manifests, which should get rid of these issues (no more manifests for ebuilds).

Can you please check again?

**Comment by joostruis** [comment]
Dropping alpha1 is fine. I can check in a few minutes.

**Comment by joostruis** [comment]
It seems fine now! 

Thanks && yep thin manifests seem to be a good solution for this overlay. I noticed this earlier but never thought about bringing it up. (o:
