### ISSUE TITLE
cosmic-de/cosmic-notifications error: could not load Cargo configuration

### ISSUE THREAD

**Issue by joostruis** [fsvm88/cosmic-overlay#7]
Bumping into this. I'll attach my full log.

[layerscosmic100alpha1_spec-build.log](https://github.com/user-attachments/files/16564348/layerscosmic100alpha1_spec-build.log)

**Comment by joostruis** [comment]
I pulled the docker build container to investigate a bit further but don't know what is going on here. This is the content of that file:

`64f9029d7898 /var/tmp/portage/cosmic-de/cosmic-notifications-9999/work/cargo_home # cat config.toml 
[source.gentoo]
directory = "/var/tmp/portage/cosmic-de/cosmic-notifications-9999/work/cargo_home/gentoo"

[source.crates-io]
replace-with = "gentoo"
local-registry = "/nonexistent"

[net]
offline = true

[build]
rustflags = "-C strip=none -C linker=x86_64-pc-linux-gnu-gcc -C link-arg=-Wl,-O1 -C link-arg=-Wl,--as-needed   "
jobs = 24
incremental = false

[term]
verbose = true`

**Comment by fsvm88** [comment]
This is what I see in the build folder on my host system:

```
╰─>$ cat cargo_home/config.toml
[source.gentoo]
directory = "/var/tmp/portage/cosmic-de/cosmic-notifications-9999/work/cargo_home/gentoo"

[source.crates-io]
replace-with = "gentoo"
local-registry = "/nonexistent"

[net]
offline = true

[build]
jobs = 36
incremental = false

[term]
verbose = true


╰─>$ cat cosmic-notifications-9999/.cargo/config.toml
[build]
rustflags = ["--cfg", "tokio_unstable"]
rustdocflags = ["--cfg", "tokio_unstable"]
```

I suppose that the issue is that in your `cargo_home/config.toml` rustflags are a string, but in `.cargo/config.toml` they are an array, so cargo doesn't know how to merge them:
```
[build]
rustflags = "-C strip=none -C linker=x86_64-pc-linux-gnu-gcc -C link-arg=-Wl,-O1 -C link-arg=-Wl,--as-needed   "
```

I don't know where `rustflags` comes from on your build container. If you can share a guide on how you're building the packages, I can try to help.

**Comment by joostruis** [comment]
Thanks for investigating things. This week I'm AFK. Going to check things next week!

**Comment by joostruis** [comment]
I am a bit clueless about how my build env got into this problem. However. Now that newer rust 1.8.x is in Portage tree and if I use the rust-bin version of that I do not run into this Cargo issue.

**Comment by fsvm88** [comment]
Great you got it working :)

In case you find time/want/need to debug further, these are my USEs. I don't believe any of them has an impact, but perhaps it can help you debug.

```
[ebuild   R   ~] dev-lang/rust-1.80.1:stable/1.80::cosmic-overlay  USE="clippy lto profiler rust-analyzer rust-src rustfmt system-bootstrap system-llvm verify-sig wasm (-big-endian) -debug -dist -doc (-llvm-libunwind) (-miri) -nightly (-parallel-compiler) -test" ABI_X86="32 (64) (-x32)" CPU_FLAGS_X86="sse2" LLVM_TARGETS="AMDGPU BPF SPIRV WebAssembly (X86) -AArch64 -ARC -ARM -AVR -CSKY -DirectX -Hexagon -Lanai -LoongArch -M68k -MSP430 -Mips -NVPTX -PowerPC -RISCV -Sparc -SystemZ -VE -XCore -Xtensa" 0 KiB
```
