### ISSUE TITLE
journald is mandatory

### ISSUE THREAD

**Issue by pcallycat** [fsvm88/cosmic-overlay#9]
per system76 interviews, systemd should be optional, however can't launch build due to journald being missing on an openrc install

**Comment by fsvm88** [comment]
Hi,

I had a quick look, and I may have missed something, but there should be no mandatory systemd support anywhere in the *DEPENDS. It is set up in the RDEPENDS from the eclass via USE=systemd.

Which specific project are you talking about? Perhaps I may need to introduce USE support for features.

**Comment by pcallycat** [comment]
I don't believe it's pulling in packages it shouldn't.  To that end, I
beleive your ebuilds are correct.  I think there's maybe a compile time
option or some other configuration to instruct the software at build
time not to expect journald to exist.  I run into the same issue if I
compile manually, though I haven't gone farther than a test run to see
if the software build is just pulling in crates whether systemd is
present on a system or not.  I know they made it possible to use
without systemd in order to get it working on FreeBSD, but I've not had
the luxury of time to research what is needed as of yet.

**Comment by nater1983** [comment]
if it is in cosmic-comp you need to have a patch and --no-default-features added
same with cosmic-session

`diff --git a/src/systemd.rs b/src/systemd.rs
index 9d617d5..6ee03da 100644
--- a/src/systemd.rs
+++ b/src/systemd.rs
@@ -11,22 +11,22 @@ use zbus_systemd::systemd1::ManagerProxy as SystemdManagerProxy;
 
 pub async fn set_systemd_environment(key: &str, value: &str) {
 	run_optional_command(
-		"systemctl",
-		&["--user", "set-environment", &format!("{key}={value}")],
+		"loginctl",
+		&["attach", &format!("{key}={value}")],
 	)
 }
 
 pub async fn start_systemd_target() {
 	run_optional_command(
-		"systemctl",
-		&["--user", "start", "--no-block", "cosmic-session.target"],
+		"loginctl",
+		&["activate", "--ignore-inhibitors"],
 	)
 }
 
 pub fn stop_systemd_target() {
 	run_optional_command(
-		"systemctl",
-		&["--user", "stop", "--no-block", "cosmic-session.target"],
+		"loginctl",
+		&["terminate-session", "--ignore-inhibitors"],
 	)
 }
 
`

**Comment by nater1983** [comment]
I have successfully built with the help of @mac-a-r0ni the Cosmic Desktop for Slackware

**Comment by fsvm88** [comment]
Hi @pcallycat , @nater1983 : I've opened a PR with initial work: https://github.com/fsvm88/cosmic-overlay/pull/11 (thanks for directions and patch @nater1983 :) )

Can you please test this work? I don't have a non-systemd system available atm, and will take me some time to build a chroot.

**Comment by nater1983** [comment]
I only have Slackware installed and I can confirm this works..

**Comment by fsvm88** [comment]
@pcallycat I have merged the PR above, I have tested the work in a separate chroot starting with a clean stage3 with openrc and USE=elogind, all packages built fine. This also allowed me to the detect a missing dep on pipewire :)

Closing.
